project:
  type: website

website:
  title: "Test2"
  navbar:
    left:
      - href: index.qmd #you can use this to link to a separate pg, basically
        text: Home
      - about.qmd
      - href: other.qmd
        text: Otherr
      - href: map.qmd
        text: map
      - href: graph.qmd
        text: graph without codecell

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



