project:
  type: website

website:
  title: "Test2"
  navbar:
    left:
      - href: index.qmd #you can use this to link to a separate pg, basically
        text: Home
      - about.qmd
      - href: other.qmd
        text: Other
      - href: map.qmd

        text: graph without codecell
      - href: testmap.qmd
        text: testttt
      - href: newtest.qmd
        text: newtest
      - href: 2-25test.qmd

        text: 2-25
      - href: 2-25 map.qmd

        text: 2-25 map



format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



